-- MySQL Script generated by MySQL Workbench
-- 11/20/14 17:03:55
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema opf5
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `opf5` ;
CREATE SCHEMA IF NOT EXISTS `opf5` DEFAULT CHARACTER SET utf8 ;
USE `opf5` ;

-- -----------------------------------------------------
-- Table `opf5`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opf5`.`administrador` ;

CREATE TABLE IF NOT EXISTS `opf5`.`administrador` (
  `id_administrador` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_administrador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opf5`.`jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opf5`.`jugador` ;

CREATE TABLE IF NOT EXISTS `opf5`.`jugador` (
  `id_jugador` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `apodo` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_nacimiento` DATETIME NULL DEFAULT NULL,
  `handicap` INT(11) NULL DEFAULT NULL,
  `mail` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_jugador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opf5`.`amigo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opf5`.`amigo` ;

CREATE TABLE IF NOT EXISTS `opf5`.`amigo` (
  `id_amigo` BIGINT(20) NOT NULL,
  `id_jugador` BIGINT(20) NOT NULL,
  INDEX `FK_tp5tlgxpxlu7asecfjmdoqdqn` (`id_jugador` ASC),
  INDEX `FK_qn8704q6gm9nmkqa0kt246686` (`id_amigo` ASC),
  CONSTRAINT `FK_qn8704q6gm9nmkqa0kt246686`
    FOREIGN KEY (`id_amigo`)
    REFERENCES `opf5`.`jugador` (`id_jugador`),
  CONSTRAINT `FK_tp5tlgxpxlu7asecfjmdoqdqn`
    FOREIGN KEY (`id_jugador`)
    REFERENCES `opf5`.`jugador` (`id_jugador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opf5`.`condicion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opf5`.`condicion` ;

CREATE TABLE IF NOT EXISTS `opf5`.`condicion` (
  `tipo_condicion` VARCHAR(31) NOT NULL,
  `id_condicion` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `tamanio_maximo` INT(11) NULL DEFAULT NULL,
  `cantidad_jugadores` INT(11) NULL DEFAULT NULL,
  `primera_letra` VARCHAR(255) NULL DEFAULT NULL,
  `edad_maxima` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_condicion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opf5`.`partido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opf5`.`partido` ;

CREATE TABLE IF NOT EXISTS `opf5`.`partido` (
  `id_partido` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `equipos_confirmados` BIT(1) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `partido_confirmado` BIT(1) NULL DEFAULT NULL,
  `ubicacion` VARCHAR(255) NULL DEFAULT NULL,
  `id_administrador` BIGINT(20) NOT NULL,
  `id_condicion` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id_partido`),
  UNIQUE INDEX `UK_aiohbjlxm1jxoatb1w1kax1mj` (`id_condicion` ASC),
  INDEX `FK_gyox82a722ay2n8lh4q3a46x5` (`id_administrador` ASC),
  CONSTRAINT `FK_aiohbjlxm1jxoatb1w1kax1mj`
    FOREIGN KEY (`id_condicion`)
    REFERENCES `opf5`.`condicion` (`id_condicion`),
  CONSTRAINT `FK_gyox82a722ay2n8lh4q3a46x5`
    FOREIGN KEY (`id_administrador`)
    REFERENCES `opf5`.`administrador` (`id_administrador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opf5`.`calificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opf5`.`calificacion` ;

CREATE TABLE IF NOT EXISTS `opf5`.`calificacion` (
  `id_calificacion` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `critica` VARCHAR(255) NULL DEFAULT NULL,
  `valor` INT(11) NULL DEFAULT NULL,
  `id_calificador` BIGINT(20) NULL DEFAULT NULL,
  `id_jugador` BIGINT(20) NULL DEFAULT NULL,
  `id_partido` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_calificacion`),
  INDEX `FK_rvetgwlcmbs6yj9yv0hoyed9x` (`id_calificador` ASC),
  INDEX `FK_ea661s9divpk2cfpmg264ak09` (`id_jugador` ASC),
  INDEX `FK_rddb428acrrfvuv86c47ftxq9` (`id_partido` ASC),
  CONSTRAINT `FK_ea661s9divpk2cfpmg264ak09`
    FOREIGN KEY (`id_jugador`)
    REFERENCES `opf5`.`jugador` (`id_jugador`),
  CONSTRAINT `FK_rddb428acrrfvuv86c47ftxq9`
    FOREIGN KEY (`id_partido`)
    REFERENCES `opf5`.`partido` (`id_partido`),
  CONSTRAINT `FK_rvetgwlcmbs6yj9yv0hoyed9x`
    FOREIGN KEY (`id_calificador`)
    REFERENCES `opf5`.`jugador` (`id_jugador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opf5`.`denegacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opf5`.`denegacion` ;

CREATE TABLE IF NOT EXISTS `opf5`.`denegacion` (
  `id_denegacion` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `dia` DATETIME NULL DEFAULT NULL,
  `motivo` VARCHAR(255) NULL DEFAULT NULL,
  `id_administrador` BIGINT(20) NULL DEFAULT NULL,
  `id_jugador` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_denegacion`),
  INDEX `FK_6jc81ubew6xe4qt6xgh3kraw8` (`id_administrador` ASC),
  INDEX `FK_di4dm0qtucuecxwgbqdlrqeln` (`id_jugador` ASC),
  CONSTRAINT `FK_6jc81ubew6xe4qt6xgh3kraw8`
    FOREIGN KEY (`id_administrador`)
    REFERENCES `opf5`.`administrador` (`id_administrador`),
  CONSTRAINT `FK_di4dm0qtucuecxwgbqdlrqeln`
    FOREIGN KEY (`id_jugador`)
    REFERENCES `opf5`.`jugador` (`id_jugador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opf5`.`equipo_a`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opf5`.`equipo_a` ;

CREATE TABLE IF NOT EXISTS `opf5`.`equipo_a` (
  `id_partido` BIGINT(20) NOT NULL,
  `id_jugador` BIGINT(20) NOT NULL,
  INDEX `FK_l0ktx5lrpc8wmpwfgrhe7hw0j` (`id_jugador` ASC),
  INDEX `FK_okkea9xl0bahqy0tlkb8wybe1` (`id_partido` ASC),
  CONSTRAINT `FK_l0ktx5lrpc8wmpwfgrhe7hw0j`
    FOREIGN KEY (`id_jugador`)
    REFERENCES `opf5`.`jugador` (`id_jugador`),
  CONSTRAINT `FK_okkea9xl0bahqy0tlkb8wybe1`
    FOREIGN KEY (`id_partido`)
    REFERENCES `opf5`.`partido` (`id_partido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opf5`.`equipo_b`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opf5`.`equipo_b` ;

CREATE TABLE IF NOT EXISTS `opf5`.`equipo_b` (
  `id_partido` BIGINT(20) NOT NULL,
  `id_jugador` BIGINT(20) NOT NULL,
  INDEX `FK_rfv6qcq8chqkfa5k0p9ladk5i` (`id_jugador` ASC),
  INDEX `FK_negx5w5uvou5kdj1bvfp1xfm4` (`id_partido` ASC),
  CONSTRAINT `FK_negx5w5uvou5kdj1bvfp1xfm4`
    FOREIGN KEY (`id_partido`)
    REFERENCES `opf5`.`partido` (`id_partido`),
  CONSTRAINT `FK_rfv6qcq8chqkfa5k0p9ladk5i`
    FOREIGN KEY (`id_jugador`)
    REFERENCES `opf5`.`jugador` (`id_jugador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opf5`.`hibernate_sequences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opf5`.`hibernate_sequences` ;

CREATE TABLE IF NOT EXISTS `opf5`.`hibernate_sequences` (
  `sequence_name` VARCHAR(255) NULL DEFAULT NULL,
  `sequence_next_hi_value` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opf5`.`infraccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opf5`.`infraccion` ;

CREATE TABLE IF NOT EXISTS `opf5`.`infraccion` (
  `id_infraccion` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `dia` DATETIME NULL DEFAULT NULL,
  `motivo` VARCHAR(255) NULL DEFAULT NULL,
  `id_jugador` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_infraccion`),
  INDEX `FK_cvlo3tgc0wqmtmqqaan59jkx9` (`id_jugador` ASC),
  CONSTRAINT `FK_cvlo3tgc0wqmtmqqaan59jkx9`
    FOREIGN KEY (`id_jugador`)
    REFERENCES `opf5`.`jugador` (`id_jugador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opf5`.`inscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opf5`.`inscripcion` ;

CREATE TABLE IF NOT EXISTS `opf5`.`inscripcion` (
  `DTYPE` VARCHAR(31) NOT NULL,
  `id_inscripcion` BIGINT(20) NOT NULL,
  `ha_jugado` BIT(1) NULL DEFAULT NULL,
  `id_jugador` BIGINT(20) NULL DEFAULT NULL,
  `id_partido` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_inscripcion`),
  INDEX `FK_b8mf435i623ofwu0s89ek5jtj` (`id_jugador` ASC),
  INDEX `FK_9ctnqkyydd4e3r3dw3suf241l` (`id_partido` ASC),
  CONSTRAINT `FK_9ctnqkyydd4e3r3dw3suf241l`
    FOREIGN KEY (`id_partido`)
    REFERENCES `opf5`.`partido` (`id_partido`),
  CONSTRAINT `FK_b8mf435i623ofwu0s89ek5jtj`
    FOREIGN KEY (`id_jugador`)
    REFERENCES `opf5`.`jugador` (`id_jugador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opf5`.`jugador_x_partido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opf5`.`jugador_x_partido` ;

CREATE TABLE IF NOT EXISTS `opf5`.`jugador_x_partido` (
  `id_partido` BIGINT(20) NOT NULL,
  `id_jugador` BIGINT(20) NOT NULL,
  INDEX `FK_om88ha9nnl7kvrg4w92j7f8fk` (`id_jugador` ASC),
  INDEX `FK_r3kchv2ogakdqv60lxtfevqam` (`id_partido` ASC),
  CONSTRAINT `FK_om88ha9nnl7kvrg4w92j7f8fk`
    FOREIGN KEY (`id_jugador`)
    REFERENCES `opf5`.`jugador` (`id_jugador`),
  CONSTRAINT `FK_r3kchv2ogakdqv60lxtfevqam`
    FOREIGN KEY (`id_partido`)
    REFERENCES `opf5`.`partido` (`id_partido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opf5`.`propuesta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opf5`.`propuesta` ;

CREATE TABLE IF NOT EXISTS `opf5`.`propuesta` (
  `id_propuesta` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_administrador` BIGINT(20) NULL DEFAULT NULL,
  `id_jugador` BIGINT(20) NOT NULL,
  `id_partido` BIGINT(20) NOT NULL,
  `id_inscripcion` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id_propuesta`),
  UNIQUE INDEX `UK_nwn5rnhlt5d04fh9514772l4y` (`id_jugador` ASC),
  UNIQUE INDEX `UK_ekmoqwmprnwmnwhnt7l4c57l2` (`id_partido` ASC),
  UNIQUE INDEX `UK_gqs8vl3yh41s48gxs41onj36x` (`id_inscripcion` ASC),
  INDEX `FK_9mcd229wvkpm0ipcmmllago0m` (`id_administrador` ASC),
  CONSTRAINT `FK_9mcd229wvkpm0ipcmmllago0m`
    FOREIGN KEY (`id_administrador`)
    REFERENCES `opf5`.`administrador` (`id_administrador`),
  CONSTRAINT `FK_ekmoqwmprnwmnwhnt7l4c57l2`
    FOREIGN KEY (`id_partido`)
    REFERENCES `opf5`.`partido` (`id_partido`),
  CONSTRAINT `FK_gqs8vl3yh41s48gxs41onj36x`
    FOREIGN KEY (`id_inscripcion`)
    REFERENCES `opf5`.`inscripcion` (`id_inscripcion`),
  CONSTRAINT `FK_nwn5rnhlt5d04fh9514772l4y`
    FOREIGN KEY (`id_jugador`)
    REFERENCES `opf5`.`jugador` (`id_jugador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `opf5` ;

-- -----------------------------------------------------
-- Placeholder table for view `opf5`.`jugadores_malos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opf5`.`jugadores_malos` (`id_jugador` INT, `apodo` INT, `fecha_nacimiento` INT, `handicap` INT, `mail` INT, `nombre` INT);

-- -----------------------------------------------------
-- Placeholder table for view `opf5`.`jugadores_pueden_mejorar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opf5`.`jugadores_pueden_mejorar` (`id_jugador` INT, `apodo` INT, `fecha_nacimiento` INT, `handicap` INT, `mail` INT, `nombre` INT);

-- -----------------------------------------------------
-- Placeholder table for view `opf5`.`jugadores_traicioneros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opf5`.`jugadores_traicioneros` (`id_jugador` INT, `apodo` INT, `fecha_nacimiento` INT, `handicap` INT, `mail` INT, `nombre` INT);

-- -----------------------------------------------------
-- procedure bajarse
-- -----------------------------------------------------

USE `opf5`;
DROP procedure IF EXISTS `opf5`.`bajarse`;

DELIMITER $$
USE `opf5`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `bajarse`(
	IN _id_jugador INT,
	IN _id_partido INT,
	IN _id_reemplazo INT
)
BEGIN
	IF _id_reemplazo IS NOT NULL
	THEN
		DELETE FROM opf5.jugador_x_partido
		WHERE id_jugador = _id_jugador
		AND id_partido = _id_partido;
		INSERT INTO opf5.jugador_x_partido(id_partido, id_jugador)
		VALUES(_id_partido, _id_reemplazo);
	ELSE
		INSERT INTO opf5.infraccion(id_jugador, motivo)
		VALUES (_id_jugador, "No ofreció reemplazo.");
	END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function edad_actual
-- -----------------------------------------------------

USE `opf5`;
DROP function IF EXISTS `opf5`.`edad_actual`;

DELIMITER $$
USE `opf5`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `edad_actual`(birthdate DATE) RETURNS int(11)
    DETERMINISTIC
RETURN YEAR(CURDATE()) - YEAR(birthdate) - (DATE_FORMAT(CURDATE(), '%m%d') < DATE_FORMAT(birthdate, '%m%d'))$$

DELIMITER ;

-- -----------------------------------------------------
-- View `opf5`.`jugadores_malos`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `opf5`.`jugadores_malos` ;
DROP TABLE IF EXISTS `opf5`.`jugadores_malos`;
USE `opf5`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `opf5`.`jugadores_malos` AS select `opf5`.`jugador`.`id_jugador` AS `id_jugador`,`opf5`.`jugador`.`apodo` AS `apodo`,`opf5`.`jugador`.`fecha_nacimiento` AS `fecha_nacimiento`,`opf5`.`jugador`.`handicap` AS `handicap`,`opf5`.`jugador`.`mail` AS `mail`,`opf5`.`jugador`.`nombre` AS `nombre` from `opf5`.`jugador` where (`opf5`.`jugador`.`handicap` <= 5);

-- -----------------------------------------------------
-- View `opf5`.`jugadores_pueden_mejorar`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `opf5`.`jugadores_pueden_mejorar` ;
DROP TABLE IF EXISTS `opf5`.`jugadores_pueden_mejorar`;
USE `opf5`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `opf5`.`jugadores_pueden_mejorar` AS select `jugadores_malos`.`id_jugador` AS `id_jugador`,`jugadores_malos`.`apodo` AS `apodo`,`jugadores_malos`.`fecha_nacimiento` AS `fecha_nacimiento`,`jugadores_malos`.`handicap` AS `handicap`,`jugadores_malos`.`mail` AS `mail`,`jugadores_malos`.`nombre` AS `nombre` from `opf5`.`jugadores_malos` where (`edad_actual`(`jugadores_malos`.`fecha_nacimiento`) < 25);

-- -----------------------------------------------------
-- View `opf5`.`jugadores_traicioneros`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `opf5`.`jugadores_traicioneros` ;
DROP TABLE IF EXISTS `opf5`.`jugadores_traicioneros`;
USE `opf5`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `opf5`.`jugadores_traicioneros` AS select `j`.`id_jugador` AS `id_jugador`,`j`.`apodo` AS `apodo`,`j`.`fecha_nacimiento` AS `fecha_nacimiento`,`j`.`handicap` AS `handicap`,`j`.`mail` AS `mail`,`j`.`nombre` AS `nombre` from (`opf5`.`jugador` `j` join `opf5`.`infraccion` `i` on((`j`.`id_jugador` = `i`.`id_jugador`))) where (month(`j`.`fecha_nacimiento`) = month((curdate() - interval 1 month))) having (count(`i`.`id_infraccion`) > 3);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
